[window]
opacity = 0.8
padding = { x = 15, y = 0 }
dynamic_padding = false

[colors.primary]
background = "#1D1D20"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
